enabled: true
image:
  repository: ""
  tag: "latest"
  pullPolicy: Always
replicas: 1
service:
  type: NodePort
  port: 8086  # 모듈별 포트 설정
  nodePort: 30086
env:
  springProfile: "k3s-dev"
  dbHost: "modeunsa-infra-mysql"
  dbPort: "3306"
  dbName: ""
  redisHost: "modeunsa-infra-redis"
  redisPort: "6379"
  kafkaBootstrapServers: "modeunsa-infra-kafka:9092"
  jvmThreadCount: "120"
  eventPublisherType: ""
  eventConsumerType: ""
  esHost: "modeunsa-infra-elasticsearch"
  esPort: "9200"
secrets:
  dbUsername: "root"
  dbPassword: ""
  redisPassword: ""
  jwtSecret: ""
  kakaoClientId: ""
  kakaoClientSecret: ""
  naverClientId: ""
  naverClientSecret: ""
  awsAccessKey: ""
  awsSecretKey: ""
  encryptionMasterKey: ""
  tossPaymentsSecretKey: ""
  internalApiKey: ""
javaOpts: "-Xmx128m -XX:MaxMetaspaceSize=192m -XX:ReservedCodeCacheSize=24m -Xss512k"
resources:
  requests:
    cpu: 90m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 512Mi
