enabled: true
image:
  repository: ""
  tag: "latest"
  pullPolicy: Always
replicas: 1
service:
  type: NodePort
  port: 8081
  nodePort: 30081
env:
  springProfile: "k3s-dev"
  dbHost: "modeunsa-infra-mysql"
  dbPort: "3306"
  dbName: ""
  redisHost: "modeunsa-infra-redis"
  redisPort: "6379"
  kafkaBootstrapServers: "modeunsa-infra-kafka:9092"
  eventPublisherType: ""
  eventConsumerType: ""
secrets:
  dbUsername: "root"
  dbPassword: ""
  redisPassword: ""
  jwtSecret: ""
  kakaoClientId: ""
  kakaoClientSecret: ""
  naverClientId: ""
  naverClientSecret: ""
  awsAccessKey: ""
  awsSecretKey: ""
  encryptionMasterKey: ""
  tossPaymentsSecretKey: ""
  internalApiKey: ""
  openaiApiKey: ""
javaOpts: "-Xmx160m -XX:MaxMetaspaceSize=160m -XX:ReservedCodeCacheSize=32m -Xss512k"
resources:
  requests:
    cpu: 90m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 512Mi
