{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-exporter.fullname" . }}-secret
  labels:
    {{- include "mysql-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Go MySQL driver DSN: user:password@tcp(host:port)/
  DATA_SOURCE_NAME: "{{ .Values.mysql.user }}:{{ .Values.mysql.password }}@tcp({{ .Values.mysql.host }}:{{ .Values.mysql.port }})/"
{{- end }}