version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - modeunsa-net
    depends_on:
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - modeunsa-net
    volumes:
      - mysql_data:/var/lib/mysql

  app-blue:
    image: ${DOCKER_IMAGE}
    container_name: app-blue
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PWD}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PWD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - modeunsa-net
    profiles:
      - blue

  app-green:
    image: ${DOCKER_IMAGE}
    container_name: app-green
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PWD}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PWD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - modeunsa-net
    profiles:
      - green

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - modeunsa-net
    command: redis-server --requirepass ${REDIS_PWD} --appendonly yes
    volumes:
      - redis_data:/data

networks:
  modeunsa-net:
    driver: bridge

volumes:
  redis_data: