version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-blue
    networks:
      - modeunsa-net

  app-blue:
    image: ${DOCKER_IMAGE}
    container_name: app-blue
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=redis
    networks:
      - modeunsa-net

  app-green:
    image: ${DOCKER_IMAGE}
    container_name: app-green
    ports:
      - "8082:8080"
    environment:
      - REDIS_HOST=redis
    networks:
      - modeunsa-net
    profiles:
      - green

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - modeunsa-net

networks:
  modeunsa-net:
    driver: bridge