version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - modeunsa-net
    depends_on:
      - redis

  app-blue:
    image: ${DOCKER_IMAGE}
    container_name: app-blue
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PWD}
    networks:
      - modeunsa-net
    profiles:
      - blue

  app-green:
    image: ${DOCKER_IMAGE}
    container_name: app-green
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PWD}
    networks:
      - modeunsa-net
    profiles:
      - green

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - modeunsa-net
    command: redis-server --requirepass ${REDIS_PWD} --appendonly yes
    volumes:
      - redis_data:/data

networks:
  modeunsa-net:
    driver: bridge

volumes:
  redis_data: