spring:
  config:
    import: optional:file:.env.k3s-dev[.properties]
  datasource:
    url: jdbc:mysql://127.0.0.1:30306/${DB_NAME:modeunsa}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

#  kafka:
#    listener:
#      auto-startup: false

custom:
  swagger:
    serverUrl: http://localhost:8080
    description: "File Local Server"
  security:
    permit-all: false
    permit-urls:
      # ========== 개발 도구 ==========
      - /h2-console/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /
      - /favicon.ico
      - /error

      # ========== 헬스체크 ==========
      - /actuator/health
      - /actuator/prometheus

springdoc:
  swagger-ui:
    persistAuthorization: true