enabled: true
image:
  repository: ""
  tag: "latest"
  pullPolicy: Always
replicas: 1
service:
  type: NodePort
  port: 8088
  nodePort: 30088
env:
  springProfile: "k3s-dev"
  dbHost: "modeunsa-infra-mysql"
  dbPort: "3306"
  dbName: ""
  redisHost: "modeunsa-infra-redis"
  redisPort: "6379"
  kafkaBootstrapServers: "modeunsa-infra-kafka:9092"
  eventPublisherType: ""
  eventConsumerType: ""
  esHost: "modeunsa-infra-elasticsearch"
  esPort: "9200"
secrets:
  dbUsername: "root"
  dbPassword: ""
  redisPassword: ""
  jwtSecret: ""
  kakaoClientId: ""
  kakaoClientSecret: ""
  naverClientId: ""
  naverClientSecret: ""
  awsAccessKey: ""
  awsSecretKey: ""
  encryptionMasterKey: ""
  tossPaymentsSecretKey: ""
  internalApiKey: ""
javaOpts: "-Xmx48m -XX:MaxMetaspaceSize=160m -XX:ReservedCodeCacheSize=16m -Xss512k"
resources:
  requests:
    cpu: 70m
    memory: 160Mi
  limits:
    cpu: 220m
    memory: 384Mi
