spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:your_db_name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update # 추후 validate로 변경 검토
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: KAKAO
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: NAVER
            scope:
              - name
              - email
              - mobile
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  elasticsearch:
    uris:
      - http://elasticsearch:9200

custom:
  security:
    permit-all: false
    permit-urls:
      # Swagger (운영에서 제거 고려)
      - /swagger-ui/**
      - /v3/api-docs/**
      - /
      - /favicon.ico

      # 내부 통신용 API
      - /api/v1/orders/internal/**
      - /api/v1/products/validate-order
      - /api/v1/products/stock

      # 인증 API
      - /api/v1/auths/oauth/*/url
      - /api/v1/auths/login/**
      - /api/v1/auths/reissue
      - /api/v1/test/roles/**
      - /login/oauth2/code/**

      # 헬스체크
      - /actuator/health

      # 콘텐츠
      - /api/v1/contents/**

      # 결제 콜백
      - /api/v1/payments/*/payment/confirm/by/tossPayments
      - /api/v1/payments/**
    oauth2:
      allowed-redirect-domains:
        - localhost
        - 52.79.155.221
  cors:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never