security:
  permit-all: false
  permit-urls: /api/v1/auths/oauth/**
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000   # 30분
  refresh-token-expiration: 604800000 # 7일