spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/modeunsa
    username: root
    password: ${MYSQL_ROOT_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: KAKAO
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: NAVER
            scope:
              - name
              - email
              - mobile
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  elasticsearch:
    uris:
      - http://localhost:9200

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8080}
  security:
    permit-all: false
    permit-urls:
      - /h2-console/**
      - /swagger-ui/**
      - /favicon.ico
      - /error
      - /login/oauth2/code/**
      - /v3/api-docs/**
      - /api/v1/auths/**
      - /api/v1/products/**
      - /api/v1/orders/**
      - /api/v1/payments/**
      - /api/v1/contents/**
      - /api/v1/settlements/**
      - /api/v1/file-uploads/**
      - /settlement/**
      - /api/v1/settlements/flow/**
      - /.well-known/**
    oauth2:
      allowed-redirect-domains:
        - localhost
        - 127.0.0.1
  cors:
    enabled: true
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
