spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:30306}/${DB_NAME:modeunsa}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:${MYSQL_ROOT_PASSWORD:}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: KAKAO
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: NAVER
            scope:
              - name
              - email
              - mobile
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  elasticsearch:
    uris:
      - ${SPRING_ELASTICSEARCH_URIS:http://127.0.0.1:30920}

custom:
  swagger:
    serverUrl: ${SWAGGER_SERVER_URL:http://127.0.0.1:8080}
    description: "Local Server"
  security:
    permit-all: false
    permit-urls:
      # ========== 개발 도구 ==========
      - /h2-console/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /
      - /favicon.ico

      # ========== 인증 API ==========
      - /api/v1/auths/oauth/*/url
      - /api/v1/auths/login/**
      - /api/v1/auths/reissue
      - /api/v1/auths/dev/**
      - /login/oauth2/code/**
      - /api/v1/test/roles/**

      # ========== 헬스체크 ==========
      - /actuator/health
      - /actuator/prometheus

      # ========== 콘텐츠 ==========
      - /api/v1/contents/**
    oauth2:
      allowed-redirect-domains:
        - localhost
        - 127.0.0.1
  cors:
    enabled: true
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - http://localhost:8080
      - http://127.0.0.1:8080
      - http://localhost:30080
