{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymentApi.fullname" . }}
  labels:
    {{- include "paymentApi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "paymentApi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paymentApi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: payment-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            # Spring Profile
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfile | quote }}
            # Database
            - name: DB_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.env.dbPort | quote }}
            - name: DB_NAME
              value: {{ .Values.env.dbName | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.env.dbName | quote }}
            # Redis
            - name: REDIS_HOST
              value: {{ .Values.env.redisHost | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.redisPort | quote }}
            {{- if .Values.javaOpts }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaOpts | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "paymentApi.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            periodSeconds: 30
{{- end }}
