enabled: true
image:
  tag: "latest"
service:
  type: NodePort
  nodePort: 30085
kafka:
  bootstrapServers: "modeunsa-infra-kafka:9092"
server:
  contextPath: "/kafka-ui"
javaOpts: "-Xmx256m"
resources:
  requests:
    cpu: 15m
    memory: 64Mi
  limits:
    cpu: 80m
    memory: 192Mi
