{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafkaui.fullname" . }}
  labels:
    {{- include "kafkaui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9080
      targetPort: 8080
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "kafkaui.fullname" . }}
{{- end }}
