spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:modeunsa-infra-mysql}:${DB_PORT:3306}/${DB_NAME:modeunsa}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST:modeunsa-infra-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

custom:
  swagger:
    serverUrl: https://modeunsa.store
    description: "Production Server"
  security:
    permit-all: false
    permit-urls:
      # ========== Swagger (prod에서는 제한 가능) ==========
      - /swagger-ui/**
      - /v3/api-docs/**
      - /
      - /favicon.ico
      - /error

      # ========== 인증 API ==========
      - /api/v1/auths/me
      - /api/v1/auths/oauth/*/url
      - /api/v1/auths/login/**
      - /api/v1/auths/dev/**
      - /api/v1/auths/reissue
      - /login/oauth2/code/**

      # ========== 헬스체크 ==========
      - /actuator/health
      - /actuator/prometheus

      # ========== 토스 웹훅 ===========
      - /api/v2/payments/webhooks/toss
  cors:
    enabled: true
    allowed-origins:
      - https://modeunsa.store
      - http://modeunsa.store

springdoc:
  swagger-ui:
    persistAuthorization: true

app:
  cookie:
    secure: true
    http-only: true
    same-site: Strict
