{{- if .Values.enabled }}
{{- range $name, $route := .Values.routes }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "traefik.fullname" $ }}-{{ $name }}
  labels:
    {{- include "traefik.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - {{ $name }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $.Release.Name }}-{{ $route.service }}
          port: {{ $route.port }}
{{- end }}
{{- end }}
