apiVersion: v2
name: modeunsa-app
description: Modeunsa Application
type: application
version: 0.1.0

dependencies:
  - name: api-gateway-api
    version: "0.1.0"
    condition: api-gateway-api.enabled
  - name: settlement-api
    version: "0.1.0"
    condition: settlement-api.enabled
  - name: payment-api
    version: "0.1.0"
    condition: payment-api.enabled
  - name: order-api
    version: "0.1.0"
    condition: order-api.enabled
  - name: frontend
    version: 0.1.0
    condition: frontend.enabled
  - name: member-api
    version: "0.1.0"
    condition: member-api.enabled
  - name: product-api
    version: "0.1.0"
    condition: product-api.enabled
  - name: file-api
    version: "0.1.0"
    condition: file-api.enabled
  - name: inventory-api
    version: "0.1.0"
    condition: inventory-api.enabled
