apiVersion: v2
name: modeunsa-app
description: Modeunsa Application
type: application
version: 0.1.0

dependencies:
  - name: api
    version: "0.1.0"
    condition: api.enabled
  - name: settlement-api
    version: "0.1.0"
    condition: settlement-api.enabled
  - name: frontend
    version: 0.1.0
    condition: frontend.enabled
  - name: member-api
    version: "0.1.0"
    condition: member-api.enabled
