# prod 환경 - EC2 + k3s (ClusterIP + Ingress)
backendCommonProd:
  springProfile: &backendCommonProdSpringProfile "k3s-prod"

api:
  enabled: false

api-gateway-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile

settlement-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile

payment-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile

order-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile

frontend:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

ingress:
  enabled: true

member-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile

product-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile

file-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile

inventory-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile
