# prod 환경 - EC2 + k3s (ClusterIP + Ingress)
backendCommonProd:
  springProfile: &backendCommonProdSpringProfile "k3s-prod"

api-gateway-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile
  resources:
    limits:
      cpu: 1
      memory: 1536Mi

settlement-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile
  resources:
    limits:
      cpu: 1
      memory: 1536Mi

frontend:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

ingress:
  enabled: true

member-api:
  enabled: true
  image:
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  env:
    springProfile: *backendCommonProdSpringProfile
  resources:
    limits:
      cpu: 1
      memory: 1536Mi