{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inventoryApi.fullname" . }}
  labels:
    {{- include "inventoryApi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "inventoryApi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inventoryApi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: inventory-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfile | quote }}
            - name: DB_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.env.dbPort | quote }}
            - name: DB_NAME
              value: {{ .Values.env.dbName | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.env.dbName | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.redisHost | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.redisPort | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.kafkaBootstrapServers | quote }}
            - name: BPL_JVM_THREAD_COUNT
              value: {{ .Values.env.jvmThreadCount | quote }}
            - name: EVENT_PUBLISHER_TYPE
              value: {{ .Values.env.eventPublisherType | quote }}
            - name: EVENT_CONSUMER_TYPE
              value: {{ .Values.env.eventConsumerType | quote }}
            - name: ES_HOST
              value: {{ .Values.env.esHost | quote }}
            - name: ES_PORT
              value: {{ .Values.env.esPort | quote }}
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://{{ .Values.env.esHost }}:{{ .Values.env.esPort }}"
            {{- if .Values.javaOpts }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaOpts | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "inventoryApi.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            timeoutSeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            periodSeconds: 30
{{- end }}
