{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventoryApi.fullname" . }}-secret
  labels:
    {{- include "inventoryApi.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  KAKAO_CLIENT_ID: {{ .Values.secrets.kakaoClientId | quote }}
  KAKAO_CLIENT_SECRET: {{ .Values.secrets.kakaoClientSecret | quote }}
  NAVER_CLIENT_ID: {{ .Values.secrets.naverClientId | quote }}
  NAVER_CLIENT_SECRET: {{ .Values.secrets.naverClientSecret | quote }}
  AWS_ACCESS_KEY: {{ .Values.secrets.awsAccessKey | quote }}
  AWS_SECRET_KEY: {{ .Values.secrets.awsSecretKey | quote }}
  ENCRYPTION_MASTER_KEY: {{ .Values.secrets.encryptionMasterKey | quote }}
  TOSS_PAYMENTS_SECRET_KEY: {{ .Values.secrets.tossPaymentsSecretKey | quote }}
  INTERNAL_API_KEY: {{ .Values.secrets.internalApiKey | quote }}
{{- end }}
