{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiGatewayApi.fullname" . }}
  labels:
    {{- include "apiGatewayApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}  # 모듈별 포트 설정
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "apiGatewayApi.selectorLabels" . | nindent 4 }}
{{- end }}
