{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "grafana.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "grafana.fullname" . }}
    spec:
      containers:
        - name: grafana
          image: "grafana/grafana:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: {{ include "grafana.fullname" . }}-secret
          env:
            - name: GF_SERVER_ROOT_URL
              value: {{ .Values.server.rootUrl | quote }}
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: {{ .Values.server.serveFromSubPath | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-pvc
{{- end }}
