{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-secret
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.auth.adminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
{{- end }}
