spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:modeunsa-infra-mysql}:${DB_PORT:3306}/modeunsa_inventory
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:modeunsa-infra-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:modeunsa-infra-kafka:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:inventory-service}
  h2:
    console:
      enabled: false

app:
  event-publisher:
    type: ${EVENT_PUBLISHER_TYPE:kafka}
  event-consumer:
    type: ${EVENT_CONSUMER_TYPE:kafka}

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

custom:
  swagger:
    serverUrl: https://modeunsa.store
    description: "Production Server"
  security:
    permit-all: false
    permit-urls:
      # ========== 개발 도구 ==========
      - /swagger-ui/**
      - /v3/api-docs/**
      - /
      - /favicon.ico
      - /error

      # ========== 헬스체크 ==========
      - /actuator/health
      - /actuator/prometheus

springdoc:
  swagger-ui:
    persistAuthorization: true

services:
  member:
    host: modeunsa-app-member-api
  auth:
    host: auth
  product:
    host: modeunsa-app-product-api
  order:
    host: modeunsa-app-order-api
  inventory:
    host: modeunsa-app-inventory-api
  payment:
    host: modeunsa-app-payment-api
  settlement:
    host: modeunsa-app-settlement-api
  file:
    host: modeunsa-app-file-api
  content:
    host: content
