enabled: true
image:
  tag: "v3.4"
resources:
  limits:
    cpu: 500m
    memory: 256Mi

entrypoints:
  mysql:
    port: 3306
    nodePort: 30306
  redis:
    port: 6379
    nodePort: 30379
  elasticsearch:
    port: 9200
    nodePort: 30920

routes:
  mysql:
    service: mysql
    port: 3306
  redis:
    service: redis
    port: 6379
  elasticsearch:
    service: elasticsearch
    port: 9200
