{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.auth.database | b64enc | quote }}
{{- end }}
