{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mysql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mysql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysql.fullname" . }}
    spec:
      containers:
        - name: mysql
          image: "mysql:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: {{ include "mysql.fullname" . }}-secret
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "mysql.fullname" . }}-pvc
{{- end }}
