spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:modeunsa-infra-mysql}:${DB_PORT:3306}/${DB_NAME:modeunsa}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false

management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

custom:
  swagger:
    serverUrl: https://modeunsa.store
    description: "Production Server"
  security:
    permit-all: false
    permit-urls:
      # ========== 개발 도구 ==========
      - /swagger-ui/**
      - /v3/api-docs/**
      - /
      - /favicon.ico
      - /error

      # ========== 인증 API ==========
      - /api/v1/auths/me
      - /api/v1/auths/oauth/*/url
      - /api/v1/auths/login/**
      - /api/v1/auths/dev/**
      - /api/v1/auths/reissue
      - /login/oauth2/code/**

      # ========== 헬스체크 ==========
      - /actuator/health
      - /actuator/prometheus

      # ========== 콘텐츠 ==========
      - /api/v1/contents/**

      # ========== 결제 ===========
      - /api/v2/payments/webhooks/toss

  cors:
    enabled: true
    allowed-origins:
      - https://modeunsa.store
      - http://modeunsa.store

springdoc:
  swagger-ui:
    persistAuthorization: true

services:
  api-gateway:
    host: modeunsa-app-api-gateway-api
  member:
    host: modeunsa-app-member-api
  auth:
    host: auth
  product:
    host: modeunsa-app-product-api
  order:
    host: modeunsa-app-order-api
  inventory:
    host: inventory
  payment:
    host: modeunsa-app-payment-api
  settlement:
    host: modeunsa-app-settlement-api
  file:
    host: file
  content:
    host: content
