spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:modeunsa}
    username: ${DB_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

custom:
  swagger:
    serverUrl: ${SWAGGER_SERVER_URL:http://localhost:8080}
    description: "Local Server"
  security:
    permit-all: false
    permit-urls:
      # ========== 개발 도구 ==========
      - /h2-console/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /
      - /favicon.ico
      - /error

      # ========== 인증 API ==========
      - /api/v1/auths/me
      - /api/v1/auths/oauth/*/url
      - /api/v1/auths/login/**
      - /api/v1/auths/reissue
      - /api/v1/auths/dev/**
      - /login/oauth2/code/**
      - /api/v1/test/roles/**

      # ========== 헬스체크 ==========
      - /actuator/health
      - /actuator/prometheus

      # ========== 콘텐츠 ==========
      - /api/v1/contents/**

      # ========== 상품 ===========
      - /api/v1/products
      - /api/v1/products/{id}
      - /api/v1/products/search
      - /api/v2/products/search
      - /api/v2/products/search/auto-complete
      - /api/v2/products/search/knn
      - /api/v2/products/search/hybrid

      # ========== 결제 ===========
      - /api/v2/payments/webhooks/toss

  cors:
    enabled: true
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - http://localhost:8080
      - http://127.0.0.1:8080

springdoc:
  swagger-ui:
    persistAuthorization: true

services:
  api-gateway:
    host: localhost
  member:
    host: localhost
  auth:
    host: localhost
  product:
    host: localhost
  order:
    host: localhost
  inventory:
    host: localhost
  payment:
    host: localhost
  settlement:
    host: localhost
  file:
    host: localhost
  content:
    host: localhost