spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

internal:
  api-key: test-internal-key

services:
  member:
    host: localhost
  auth:
    host: localhost
  product:
    host: localhost
  order:
    host: localhost
  inventory:
    host: localhost
  payment:
    host: localhost
  settlement:
    host: localhost
  file:
    host: localhost
  content:
    host: localhost