enabled: true
image:
  tag: "7-alpine"
auth:
  password: ""
service:
  type: NodePort
  nodePort: 30379
storage:
  size: 1Gi
maxmemory: "192mb"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
