{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-secret
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
